### ISSUE TITLE
Support for caching on TravisCI

### ISSUE THREAD

**Issue by utkbansal** [astropy/ci-helpers#207]
@mdanalysis is frequently facing terminated builds (because we hit the time limit - 50min) onTravisCI. Travis has rolled out support (currently beta) for [caching](https://docs.travis-ci.com/user/caching/) parts of the environment - like conda & pip installations which will help us reduce our build time significantly.

Are there any plans to support caching on TravisCI?

**Comment by bsipocz** [comment]
I probably won't have time in the near future to work on this, but PRs are welcome!

**Comment by utkbansal** [comment]
Sure! I am working on my fork and if I do get it to work, I'll send a PR.

**Comment by yeganer** [comment]
@utkbansal Did you make any progress? I'm facing a similar issue right now where we would like to cache the miniconda directory due to the amount of dependencies we have (the whole conda step takes ~120s).

What I am wondering is, if we need to step into `setup_dependencies.sh`, too, or if we can skip this step as all dependencies should already be installed.
