### ISSUE TITLE
numpy fall back on pip

### ISSUE THREAD

**Issue by kain88-de** [astropy/ci-helpers#268]
https://travis-ci.org/MDAnalysis/mdanalysis/jobs/328848140

We currently have the problem that conda-forge at the moment doesn't have the new numpy for python 3.4. It would be nice if in that instance the numpy installation could also fall back on pip. See Travis log above.

**Comment by eteq** [comment]
I like this idea, although the one concern is that it might mask problems where the issue is in the specifying of the version rather than it actually not being in conda.

Not a reason not to do it, just a reason to be careful about it.

**Comment by bsipocz** [comment]
@kain88-de - I'm a bit worried about falling back to pip, it actually turned out to be not that good idea as it seemed first, fixed many issues with it but it still have quite a few failures with corner cases. 

I've seen that you've opened a PR in conda-forge to actually build it, so would rather wait for it to became available?

**Comment by kain88-de** [comment]
It's possible to wait for the new numpy to be available on conda-forge. I had a thought this might be nice for a future numpy update.

Are there old branches/PRs left that show what has been tried?

**Comment by bsipocz** [comment]
Nothing has been tried as I recall for numpy, but had various issues with the pip fallback for the packages listed in `CONDA_DEPENDENCIES`. Arguably the numpy case should be cleaner as there is only one package to take care of, so overall I'm not fully against it, just would be nice to work out other options.

Alternatively, a long standing issue is to make the pip fall-back opt-in rather than default behaviour. With that approach I have nothing against doing it for numpy, too, I just don't have enough time lately to implement that with careful testing.
