### ISSUE TITLE
Specifying numpy in CONDA_DEPENDENCIES might cause conflict

### ISSUE THREAD

**Issue by pllim** [astropy/ci-helpers#284]
I had `CONDA_DEPENDENCIES='numpy ...'`, which caused conflict in https://travis-ci.org/spacetelescope/stginga/jobs/345804779 (xref spacetelescope/stginga#154). The conflict goes away when I remove "numpy" from that line.

I don't know if this is a bug or feature. FYI.

**Comment by bsipocz** [comment]
well, this is a bug because of a feature. Dealing with either the astropy or numpy dependencies should be done via the `ASTROPY_VERSION` and `NUMPY_VERSION` variables, listing them in `CONDA_DEPENDENCIES` confuses the script (though ideally it should be fixed at some point, we may already have an issue about this..).

**Comment by pllim** [comment]
> we may already have an issue about this

Maybe #205? Others are not obvious from the subject line (I didn't read the contents).
