### ISSUE TITLE
LATEST_ASTROPY_VERSION vs LTS

### ISSUE THREAD

**Issue by bsipocz** [astropy/ci-helpers#342]
We skip the tests when a build ask for `ASTROPY_VERSION=lts`, but the `LATEST_ASTROPY_VERSION` is also the LTS. However this logic collapses when the `LATEST_ASTROPY_VERSION` is set to LTS for python versions where the actual latest is not supported.  (e.g. currently on python 2.7 or 3.4 is someone asks for an LTS testing the build will terminate during install given that LTS is stable for that release). 

We added this logic to avoid running tests unnecessarily when the LTS and stable were the same, but I'm having regrets and seeing that there are more issues with it than perks, I suggest to remove it.

What do you think @astrofrog and @pllim?

**Comment by pllim** [comment]
👍 to removing LTS option. I tried to use it in 2 other projects but ended up abandoning it because it wasn't running. IMHO it is more explicit to set the version number in a test matrix. LTS, while convenient, is a moving target in the long run and might not be desirable.

That said, I like "development" because I know I am always getting the latest `master`.

**Comment by pllim** [comment]
Concern with removing it -- Break other packages that use it, either knowingly or not.

**Comment by bsipocz** [comment]
To be clear I've meant to to remove this cancellation, to the option 'lts'.

**Comment by pllim** [comment]
Oh... 🤔  I guess having it run every time does not hurt...
